# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Jamie's Alignment Helper")
        MainWindow.resize(1010, 698)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.camContain = QtWidgets.QFrame(self.centralwidget)
        self.camContain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.camContain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.camContain.setObjectName("camContain")
        self.horizontalLayout.addWidget(self.camContain)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.yDis = QtWidgets.QLabel(self.centralwidget)
        self.yDis.setObjectName("yDis")
        self.gridLayout.addWidget(self.yDis, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.totalDis = QtWidgets.QLabel(self.centralwidget)
        self.totalDis.setObjectName("totalDis")
        self.gridLayout.addWidget(self.totalDis, 1, 0, 1, 1)
        self.xDis = QtWidgets.QLabel(self.centralwidget)
        self.xDis.setObjectName("xDis")
        self.gridLayout.addWidget(self.xDis, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.spotSize = QtWidgets.QLabel(self.centralwidget)
        self.spotSize.setObjectName("spotSize")
        self.horizontalLayout_6.addWidget(self.spotSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.fwhm = QtWidgets.QLabel(self.centralwidget)
        self.fwhm.setObjectName("fwhm")
        self.horizontalLayout_3.addWidget(self.fwhm)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.d4sigma = QtWidgets.QLabel(self.centralwidget)
        self.d4sigma.setObjectName("d4sigma")
        self.horizontalLayout_4.addWidget(self.d4sigma)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.circularity = QtWidgets.QLabel(self.centralwidget)
        self.circularity.setObjectName("circularity")
        self.horizontalLayout_2.addWidget(self.circularity)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.xprofileContain = QtWidgets.QGroupBox(self.centralwidget)
        self.xprofileContain.setObjectName("xprofileContain")
        self.verticalLayout.addWidget(self.xprofileContain)
        self.yprofileContain = QtWidgets.QGroupBox(self.centralwidget)
        self.yprofileContain.setObjectName("yprofileContain")
        self.verticalLayout.addWidget(self.yprofileContain)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Jamie's Alignment Helper", "Jamie's Alignment Helper"))
        self.yDis.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "X distance"))
        self.label_11.setText(_translate("MainWindow", "Y distance"))
        self.label_9.setText(_translate("MainWindow", "Total Distance"))
        self.totalDis.setText(_translate("MainWindow", "TextLabel"))
        self.xDis.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Spot size"))
        self.spotSize.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "FWHM"))
        self.fwhm.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "D4σ"))
        self.d4sigma.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "Circularity"))
        self.circularity.setText(_translate("MainWindow", "TextLabel"))
        self.xprofileContain.setTitle(_translate("MainWindow", "X profile"))
        self.yprofileContain.setTitle(_translate("MainWindow", "Y profile"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

